#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Mar  7 11:58:57 2018

@author: MatsKlijn
"""

from numpy import *
from Cit_par import *
from control.matlab import*
import matplotlib.pyplot as plt

C1_asymmetric = matrix([[(CYbdot-2*mub)*b/V0,0,0,0],
                         [0,-b/(2*V0),0,0], 
                         [0,0,(-4*mub*KX2**2*b**2)/(2*V0**2),(4*mub*KXZ*b**2)/(2*V0**2)],
                         [Cnbdot*b/(V0),0,(4*mub*KXZ*b**2)/(2*V0**2),(-4*mub*KZ2**2*b**2)/(2*V0**2)]
                         ])

C2_asymmetric = matrix([[CYb, CL, CYp*b/2*V0,(CYr-4*mub)*b/(2*V0)],
                         [0,0,b/(2*V0),0],
                         [Clb,0,Clp*b/(2*V0),Clr*b/(2*V0)],
                         [Cnb,0,Cnp*b/(2*V0),Cnr*b/(2*V0)]
                         ])

C3_asymmetric = matrix([[CYda,CYdr],
                        [0,0],
                        [Clda,Cldr],
                        [Cnda,Cndr]
                        ])

#print (C1_asymmetric)
#print (C2_asymmetric)
#print (C3_asymmetric)

A_asymmetric = linalg.inv(-C1_asymmetric)*C2_asymmetric
    
#print 'A matrix is: ',A_asymmetric

B_asymmetric = linalg.inv(-C1_asymmetric)*C3_asymmetric
              
#print 'B matrix is: ',B_asymmetric

C_asymmetric = identity(4)
D_asymmetric = zeros((4,2))

sys_asymmetric=ss(A_asymmetric,B_asymmetric,C_asymmetric,D_asymmetric)

#---input to state space-------------------------------------------------------


t=linspace(0,10,100)

y=lsim(sys_asymmetric,u,t,input=0)

#----------plotting-----------------------------------------------------------
plt.figure(1)

plt.subplot(411)
plt.title('Velocity u (m/s)')
plt.plot(t,y[0][:,0],color='c',label='u')

plt.subplot(412)
plt.title('Angle of Attack alpha (degs)')
plt.plot(t,y[0][:,1]*180/pi, color='r', label='alpha')

plt.subplot(413)
plt.title('Fligth Path Angle theta (degs)')
plt.plot(t,y[0][:,2]*180/pi,color='b',label='theta')

plt.subplot(414)
plt.title('Pitch Rate q (m/s)')
plt.plot(t,y[0][:,3],color='g',label='q')
plt.plot()




