#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Mar  7 11:58:57 2018

@author: MatsKlijn
"""

from numpy import *
from Cit_par import *

C1_asymmetric = matrix([[(CYb-2*mub)*b/V0,0,0,0],
                         [0,-b/(2*V0),0,0], 
                         [0,0,(-4*mub*KX2*2*V0**2)/b**2,(4*mub*KXZ*2*V0**2)/b**2],
                         [Cnbdot*b/(V0),0,(4*mub*KXZ*2*V0**2)/b**2,(-4*mub*KZ2*2*V0**2)/b**2]
                         ])

C2_asymmetric = matrix([[CYb, CL, CYp*b/2*V0,(CYr-4*mub)*b/(2*V0)],
                         [0,0,b/(2*V0),0],
                         [Clb,0,Clp*b/(2*V0),Clr*b/(2*V0)],
                         [Cnb,0,Cnp*b/(2*V0),Cnr*b/(2*V0)]
                         ])

C3_asymmetric = matrix([[-CYda,-CYdr],
                        [0,0],
                        [-Clda,-Cldr],
                        [-Cnda,-Cndr]
                        ])

#print (C1_asymmetric)
#print (C2_asymmetric)
#print (C3_asymmetric)

A = linalg.inv(-C1_asymmetric)*C2_asymmetric
    
print 'A matrix is: ',A

B = linalg.inv(-C1_asymmetric)*C3_asymmetric
              
print 'B matrix is: ',B